heat_template_version: 2013-05-23
description: A load-balancer server
parameters:
  image:
    type: string
    description: Image used for servers
    default: ApacheJeOS.x86_64-0.0.2
  key_name:
    type: string
    description: SSH key to connect to the servers
    default: rashford
  flavor:
    type: string
    description: flavor used by the servers
    default: m1.small
  pool_id:
    type: string
    description: Pool to contact
  user_data:
    type: string
    description: Server user_data
  metadata:
    type: json
resources:
  server_name_suffix:
    type: OS::Heat::RandomString
    properties:
      length: 2
      sequence: digits
  server:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: 'Apache-$suffix'
          params:
            $suffix: {get_resource: server_name_suffix}
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      metadata: {get_param: metadata}
      user_data: {get_param: user_data}
      user_data_format: RAW
  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [server, first_address]}
      protocol_port: 80
